2025-01-19 22:37:56,220 INFO    MainThread:2001706 [wandb_setup.py:_flush():68] Current SDK version is 0.19.4
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_setup.py:_flush():68] Configure stats pid to 2001706
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_setup.py:_flush():68] Loading settings from /home/fumiyauchiyama/.config/wandb/settings
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_setup.py:_flush():68] Loading settings from /home/fumiyauchiyama/repos/x-anything/wandb/settings
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_init.py:setup_run_log_directory():624] Logging user logs to /home/fumiyauchiyama/repos/x-anything/wandb/run-20250119_223756-66pdt6jw/logs/debug.log
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_init.py:setup_run_log_directory():625] Logging internal logs to /home/fumiyauchiyama/repos/x-anything/wandb/run-20250119_223756-66pdt6jw/logs/debug-internal.log
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_init.py:init():743] calling init triggers
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_init.py:init():748] wandb.init called with sweep_config: {}
config: {'num_epochs': 2, 'save_steps': 200, 'model': {'model_name': 'vit_tiny_patch16_224', 'pretrained': False, 'drop_rate': 0.0, 'drop_path_rate': 0.1, 'preprocess': {'img_size': 224, 'interpolation': 'bicubic', 'is_training': False, 'no_aug': True}, 'vit_checkpoint': None, 'checkpoint': None}, 'optim': {'lr': 0.0008, 'betas': [0.9, 0.999], 'weight_decay': 0.1, 'warmup_iters': 250, 'total_iters': 90000, 'decay_iter_1': 60000, 'decay_iter_2': 86666}, 'train_dataset': {'jpg_dir': '/home/fumiyauchiyama/dataset/sa-1b/raw_jpg_1_20', 'json_dir': '/home/fumiyauchiyama/dataset/sa-1b/raw_json_1_20', 'num_data': 223749, 'max_mask_num': 3, 'img_size': 1024, 'max_mask_area_ratio': 0.9}}
2025-01-19 22:37:56,221 INFO    MainThread:2001706 [wandb_init.py:init():776] starting backend
2025-01-19 22:37:56,428 INFO    MainThread:2001706 [wandb_init.py:init():780] sending inform_init request
2025-01-19 22:37:56,432 INFO    MainThread:2001706 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-19 22:37:56,433 INFO    MainThread:2001706 [wandb_init.py:init():795] backend started and connected
2025-01-19 22:37:56,434 INFO    MainThread:2001706 [wandb_init.py:init():888] updated telemetry
2025-01-19 22:37:56,439 INFO    MainThread:2001706 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-01-19 22:37:56,780 ERROR   MainThread:2001706 [wandb_init.py:init():944] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-19 22:37:56,780 ERROR   MainThread:2001706 [wandb_init.py:init():1454] error in wandb.init()
Traceback (most recent call last):
  File "/home/fumiyauchiyama/anaconda3/envs/py10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1444, in init
    return wi.init(run_settings, run_config)
  File "/home/fumiyauchiyama/anaconda3/envs/py10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-19 22:37:56,788 WARNING MsgRouterThr:2001706 [router.py:message_loop():75] message_loop has been closed
